version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  ingester:
    build: .
    environment: 
      - ELASTICSEARCH_URL=http://es:9200/
    ports:
      - 8080:8080